SELECT NOME, ANO FROM FILMES --PASSO 1

SELECT NOME, ANO FROM FILMES ORDER BY ANO --PASSO 2

SELECT NOME, ANO, DURACAO FROM FILMES WHERE NOME LIKE '%DE VOLTA PARA O FUTURO%' --PASSO 3

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997 --PASSO 4

SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO > 2000 --PASSO 5

SELECT NOME, ANO, DURACAO FROM FILMES WHERE DURACAO > 100 AND DURACAO < 150 ORDER BY DURACAO ASC -- PASSO 6

SELECT ANO, COUNT(1) FROM FILMES GROUP BY ANO ORDER BY 2 DESC --PASSO 7

SELECT * FROM ATORES WHERE GENERO = 'M' --PASSO 8

SELECT * FROM ATORES WHERE GENERO = 'F' ORDER BY PRIMEIRONOME ASC -- PASSO 9

--PASSO 10
SELECT NOME, GENERO  
FROM FILMES FIL 
	INNER JOIN FILMESGENERO FGEN ON FIL.ID = FGEN.IDFILME
	INNER JOIN GENEROS GEN ON GEN.ID = FGEN.IDGENERO

--PASSO 11
SELECT NOME, GENERO 
FROM FILMES FIL 
	INNER JOIN FILMESGENERO FGEN 
		ON FIL.ID = FGEN.IDFILME
	INNER JOIN GENEROS GEN 
		ON GEN.ID = FGEN.IDGENERO
WHERE GENERO = 'Mistério'

--PASSO 12
SELECT NOME, PRIMEIRONOME, ULTIMONOME, PAPEL 
FROM FILMES FIL 
	INNER JOIN ELENCOFILME EF ON FIL.ID = EF.IDFILME
	INNER JOIN ATORES ATOR ON ATOR.ID = EF.IDATOR
